#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [ -f  "${HOME}/.iterm2_shell_integration.zsh" ]; then
    source "${HOME}/.iterm2_shell_integration.zsh"
fi

# Customize to your needs...
# Owner
export USER_NAME="andredp"

# FileSearch
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -R . }

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

# Aliases
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

## SFA
set_tenant() { FASTLANE_SKIP_UPDATE_CHECK=true TENANT=$1 SKIP_FASTFILE_IMPORT=true bundle exec fastlane change_tenant > /dev/null }
alias sfa-browns='set_tenant Browns'
alias sfa-tage='set_tenant Tage'
alias sfa-thombrowne='set_tenant ThomBrowne'

## iOS
alias rmderived='rm -rf ${HOME}/Library/Developer/Xcode/DerivedData'

# Add homebrew to the completion path
fpath=("/usr/local/bin/" $fpath)

# 10 second wait if you do something that will delete everything.
setopt RM_STAR_WAIT

export HOMEBREW_NO_AUTO_UPDATE="1"

source /usr/local/share/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export GPG_TTY=$(tty)
export PATH="/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:$PATH"

